language: ruby
rvm:
  - 1.9.2

before_script:
  - "cp config/database.sample.yml config/database.yml"
  - "psql -c 'create role seurio SUPERUSER LOGIN;' postgres"
  - "psql -c 'create database seurio_test;' -U seurio postgres"
  - "sh -e /etc/init.d/xvfb start"

env:
  - DISPLAY=:99.0

# uncomment this line if your project needs to run something other than `rake`:
script: "bundle exec rake db:migrate && bundle exec rspec spec && bundle exec cucumber && bundle exec rake jasmine:ci"

branches:
  only:
    - master
